# Generated by Django 4.1.7 on 2023-03-03 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_insurance_remove_employee_department_and_more'),
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='KarteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='karte.comment', verbose_name='リハコメント')),
                ('pain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='karte.pain', verbose_name='痛みの具合')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='患者名')),
                ('range', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='karte.range', verbose_name='可動域制限')),
            ],
        ),
    ]
