# Generated by Django 4.1.7 on 2023-03-05 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("karte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KarteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reha_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="リハビリ実施日"
                    ),
                ),
                ("comment", models.CharField(max_length=400, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
                (
                    "pain",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karte.pain",
                        verbose_name="痛みの具合",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="患者名",
                    ),
                ),
                (
                    "range",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karte.range",
                        verbose_name="可動域制限",
                    ),
                ),
                (
                    "rehaplan",
                    models.ManyToManyField(
                        blank=True, to="karte.rehaplan", verbose_name="リハ内容"
                    ),
                ),
            ],
        ),
    ]
