# Generated by Django 4.1.7 on 2023-03-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0002_comment_karteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='karteinfo',
            name='rehaplan',
            field=models.ManyToManyField(blank=True, to='karte.rehaplan', verbose_name='リハ内容'),
        ),
    ]
