# Generated by Django 4.1.7 on 2023-03-05 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_therapist_name"),
        ("karte", "0002_comment_karteinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="karteinfo",
            name="therapist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_therapist",
                to="employee.employee",
                verbose_name="担当セラピスト",
            ),
        ),
    ]
