# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0003_karteinfo_rehaplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='karteinfo',
            name='reha_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='リハビリ実施日'),
        ),
    ]
