# Generated by Django 4.1.7 on 2023-03-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0004_karteinfo_reha_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karteinfo',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='コメント'),
        ),
    ]
