# Generated by Django 4.1.5 on 2023-01-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_depart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="depart", new_name="department",
        ),
    ]
