# Generated by Django 4.1.7 on 2023-03-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_remove_employee_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="name",),
    ]
