# Generated by Django 4.1.7 on 2023-02-27 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_club_employee_club"),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="セラピスト名")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="employee", name="club",),
        migrations.DeleteModel(name="Club",),
        migrations.AddField(
            model_name="employee",
            name="therapist",
            field=models.ManyToManyField(to="employee.therapist", verbose_name="部活"),
        ),
    ]
