# Generated by Django 4.1.7 on 2023-02-27 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_therapist_remove_employee_club_delete_club_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="保険名")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="employee", name="department",),
        migrations.RemoveField(model_name="employee", name="therapist",),
        migrations.DeleteModel(name="Department",),
        migrations.AddField(
            model_name="employee",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employee.insurance",
                verbose_name="保険名",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employee.therapist",
                verbose_name="セラピスト名",
            ),
        ),
    ]
