# Generated by Django 4.1.7 on 2023-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_insurance_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='氏名'),
        ),
    ]
