# Generated by Django 4.1.7 on 2023-03-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
