# Generated by Django 4.1.7 on 2023-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("therapist_name", models.CharField(max_length=100)),
                ("health_center_name", models.CharField(max_length=100)),
                ("disability_name", models.CharField(max_length=100)),
                ("onset_date", models.DateField()),
                ("rehab_start_date", models.DateField()),
                ("chart_id", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("short_term_goal", models.TextField()),
                ("long_term_goal", models.TextField()),
                ("treatment_policy", models.TextField()),
                ("treatment_content", models.TextField()),
            ],
        ),
    ]
