# Generated by Django 4.1.7 on 2023-03-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="chart_id", new_name="disease",
        ),
        migrations.RenameField(
            model_name="patient", old_name="disability_name", new_name="insurance",
        ),
        migrations.RenameField(
            model_name="patient", old_name="health_center_name", new_name="karte_id",
        ),
        migrations.RenameField(
            model_name="patient", old_name="rehab_start_date", new_name="reha_start",
        ),
    ]
