# Generated by Django 4.1.7 on 2023-03-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_rename_chart_id_patient_disease_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="onset_date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="reha_start",
            field=models.CharField(max_length=100),
        ),
    ]
